### ISSUE TITLE
I want to archive a course I am enrolled in but get an error using your script.

### ISSUE THREAD

**Issue by gelsas** [barakagb/gb-dl#3]
```
C:\Users\gelsas\Desktop>gb-dl.py
Traceback (most recent call last):
  File "C:\Users\gelsas\AppData\Local\Programs\Python\Python37-32\Scripts\gb-dl.py", line 15, in <module>
    from blessings import Terminal
  File "c:\users\gelsas\appdata\local\programs\python\python37-32\lib\site-packages\blessings\__init__.py", line 5, in <module>
    import curses
  File "c:\users\gelsas\appdata\local\programs\python\python37-32\lib\curses\__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'
```

What do I need to do to make it work ? I am using windows

**Comment by barakagb** [comment]
It appears that python for Windows doesn't come with curses. 
try 
pip install windows-curses

**Comment by gelsas** [comment]
Thank you for this tip, that seemed to have fixed the issue but now I am getting a new error shown.

`
C:\Users\gelsas\Desktop>gb-dl.py
Traceback (most recent call last):
  File "C:\Users\gelsas\AppData\Local\Programs\Python\Python37-32\Scripts\gb-dl.py", line 15, in <module>
    from blessings import Terminal
  File "c:\users\gelsas\appdata\local\programs\python\python37-32\lib\site-packages\blessings\__init__.py", line 7, in <module>
    from fcntl import ioctl
ModuleNotFoundError: No module named 'fcntl'
`

What do I need to do to fix that ?

**Comment by barakagb** [comment]
It seems that fcntl is not available in windows .The fcntl module is a standard library available... on Linux only! You won't find it under Windows environment . I will make a version that works for windows soon...stay tuned !!!

**Comment by barakagb** [comment]
Hi , the problem is fixed ..please reinstall gb-dl .Thanks

**Comment by gelsas** [comment]
I just tried as you suggested but I still get an error. How do I fix this one ?

```
C:\Users\gelsas>gb-dl.py
Traceback (most recent call last):
  File "C:\Users\gelsas\AppData\Local\Programs\Python\Python37-32\Scripts\gb-dl.py", line 17, in <module>
    class DL:
  File "C:\Users\gelsas\AppData\Local\Programs\Python\Python37-32\Scripts\gb-dl.py", line 22, in DL
    t = Terminal()
NameError: name 'Terminal' is not defined
```

**Comment by barakagb** [comment]
fixed the issue ...please reinstall.Thanks

**Comment by gelsas** [comment]
Perfect now I can enter all the needed details but I get this error.
Does the course url need to have a specific structure?

I have posted my error message below (I change the actuall course name to examplecourse etc.

```
Enter course url : https://examplecourse.teachable.com/courses/enrolled/409999
Email : exampleemail@gmail.com
Password : examplepassword
Trying to Login ...
[-] In valid course URL.
```

Please let me know if I did something wrong.

P.S.: Thank you for making it work with windows! Thank you for beeing patient with me!

**Comment by gelsas** [comment]
Added my course url to the gb dl file and now it seems to work but I got this error:

```
Trying to Login ...
[+] Login successful.
Downloading to :C:\Users\gelsas
Collecting course information ...

Course name : Example Course name (Example Academy)
Getting course sections ...

[+] Found Section :  Introduction

Preparing  lecture 1 of 3 download ...
Preparing  lecture 2 of 3 download ...
Starting download ...
[Wistia] md3l5d83d1: Downloading JSON metadata
[download] Destination: Recording #2.mp4-md3l5d83d1.bin
[download] 100% of 29.58MiB in 00:10
Preparing  lecture 3 of 3 download ...
Starting download ...
[Wistia] pk68omr009: Downloading JSON metadata
[download] Destination: WARNING.mp4-pk68omr009.mp4
[download] 100% of 28.79MiB in 00:10
[-] Error : [WinError 2] The system cannot find the file specified '2.Facebook Ads: Understanding The Basics'

```

**Comment by barakagb** [comment]
Yes , It seems that windows has an issue with some directory names it handles them differently from Linux .  'Understanding The Basics' is in single quotes probably it wants double quotes .I'll fix it soon.

**Comment by barakagb** [comment]
The issue is fixed .Please reinstall . Thanks

**Comment by gelsas** [comment]
Course is downloading now. Thank you!

It downloaded the first 4 sections correctly but section 5-12 were detected but no content of these sections got downloaded.

Any ideas why that could be ?

best regards

**Comment by barakagb** [comment]
Did the script show downloading on section 5-12 ? or what was the message from the script.A screen shot would be much appreciated.I would need to investigate that but I would need the site name and course name you are trying to download.In the mean time try to download another course and see if it works.Thanks

**Comment by barakagb** [comment]
@gelsas I tried downloading a course and it was successful.
![image](https://user-images.githubusercontent.com/30619781/60643879-286df800-9e3d-11e9-9629-c44d61d7e367.png)
.Your section 5-12 might contain only HTML text that's why ... please confirm that so a can work on a fix.Thanks

**Comment by gelsas** [comment]
Every section is only videos:

![screenshot](https://user-images.githubusercontent.com/282734/60664082-45b4bd80-9e61-11e9-9a58-af9e6af7e9d5.png)

```
Getting course sections ...

[+] Found Section :  Introduction

Preparing  lecture 1 of 3 download ...
Preparing  lecture 2 of 3 download ...
Starting download ...
[Wistia] md3l5d83d1: Downloading JSON metadata
[download] Destination: Recording #2.mp4-md3l5d83d1.bin
[download] 100% of 29.58MiB in 00:09
Preparing  lecture 3 of 3 download ...
Starting download ...
[Wistia] pk68omr009: Downloading JSON metadata
[download] Destination: WARNING.mp4-pk68omr009.mp4
[download] 100% of 28.79MiB in 00:11

[+] Found Section :  Facebook Ads: Understanding The Basics

Preparing  lecture 1 of 4 download ...
Starting download ...
[Wistia] h6u0lrf1zb: Downloading JSON metadata
[download] Destination: Recording #58.mp4-h6u0lrf1zb.bin
[download] 100% of 69.11MiB in 00:13
Preparing  lecture 2 of 4 download ...
Starting download ...
[Wistia] sj0k8tvykh: Downloading JSON metadata
[download] Destination: Recording #5.mp4-sj0k8tvykh.bin
[download] 100% of 39.18MiB in 00:13
Preparing  lecture 3 of 4 download ...
Starting download ...
[Wistia] n6zs5ljpkq: Downloading JSON metadata
[download] Destination: Recording #3.mp4-n6zs5ljpkq.bin
[download] 100% of 6.44MiB in 00:02
Preparing  lecture 4 of 4 download ...
Starting download ...
[Wistia] ih5mhkth5x: Downloading JSON metadata
[download] Destination: Recording #4.mp4-ih5mhkth5x.bin
[download] 100% of 21.63MiB in 00:05

[+] Found Section :  Facebook Ads-Building Your First Ad

Preparing  lecture 1 of 11 download ...
Starting download ...
[Wistia] 7g8ldi8eh3: Downloading JSON metadata
[download] Recording #71.mp4-7g8ldi8eh3.bin has already been downloaded
[download] 100% of 27.60MiB
Preparing  lecture 2 of 11 download ...
Starting download ...
[Wistia] qndkbi6tqi: Downloading JSON metadata
[download] Recording #41.mp4-qndkbi6tqi.mp4 has already been downloaded
[download] 100% of 39.03MiB
Preparing  lecture 3 of 11 download ...
Starting download ...
[Wistia] 3sjyefs495: Downloading JSON metadata
[download] Recording #42.mp4-3sjyefs495.mp4 has already been downloaded
[download] 100% of 90.61MiB
Preparing  lecture 4 of 11 download ...
Starting download ...
[Wistia] gs70vph3b1: Downloading JSON metadata
[download] Recording #68.mp4-gs70vph3b1.bin has already been downloaded
[download] 100% of 55.80MiB
Preparing  lecture 5 of 11 download ...
Starting download ...
[Wistia] jt0g5uoage: Downloading JSON metadata
[download] 10000000_716662642060026_5331642701831995392_n.mp4-jt0g5uoage.bin has already been downloaded
[download] 100% of 24.49MiB
Preparing  lecture 6 of 11 download ...
Starting download ...
[Wistia] 4894da5zly: Downloading JSON metadata
[download] Recording #92.mp4-4894da5zly.bin has already been downloaded
[download] 100% of 55.01MiB
Preparing  lecture 7 of 11 download ...
Starting download ...
[Wistia] toidr1dxez: Downloading JSON metadata
[download] Part 7.mp4-toidr1dxez.bin has already been downloaded
[download] 100% of 53.40MiB
Preparing  lecture 8 of 11 download ...
Starting download ...
[Wistia] 4c1g1lqzz9: Downloading JSON metadata
[download] Recording #30.mp4-4c1g1lqzz9.bin has already been downloaded
[download] 100% of 34.58MiB
Preparing  lecture 9 of 11 download ...
Starting download ...
[Wistia] jokibn0ifx: Downloading JSON metadata
[download] Recording #31.mp4-jokibn0ifx.bin has already been downloaded
[download] 100% of 27.25MiB
Preparing  lecture 10 of 11 download ...
Starting download ...
[Wistia] hwl09p6al9: Downloading JSON metadata
[download] Recording #68.mp4-hwl09p6al9.bin has already been downloaded
[download] 100% of 29.42MiB
Preparing  lecture 11 of 11 download ...
Starting download ...
[Wistia] ronguzgddm: Downloading JSON metadata
[download] Recording #70.mp4-ronguzgddm.bin has already been downloaded
[download] 100% of 13.50MiB

[+] Found Section :  Facebook Ad - Ads Redacted Market

Preparing  lecture 1 of 2 download ...
Starting download ...
[Wistia] 16czcl1kda: Downloading JSON metadata
[download] Recording #62.mp4-16czcl1kda.bin has already been downloaded
[download] 100% of 25.40MiB
Preparing  lecture 2 of 2 download ...
Starting download ...
[Wistia] rtq8rpwiw6: Downloading JSON metadata
[download] Recording #63.mp4-rtq8rpwiw6.bin has already been downloaded
[download] 100% of 48.42MiB

[+] Found Section :  Facebook Ads- Redacted


[+] Found Section :  Facebook Ad 

Preparing  lecture 1 of 3 download ...
Starting download ...
[Wistia] 1l6scxmj3t: Downloading JSON metadata
[download] Destination: 10000000_170422310294992_5675743996844965888_n.mp4-1l6scxmj3t.mp4
[download] 100% of 17.58MiB in 00:06
Preparing  lecture 2 of 3 download ...
Starting download ...
[Wistia] w1swtms4os: Downloading JSON metadata
[download] Destination: 36142005_220816232081091_6566994932475625472_n.mp4-w1swtms4os.mp4
[download] 100% of 4.19MiB in 00:01
Preparing  lecture 3 of 3 download ...
Starting download ...
[Wistia] be0lrb2yu0: Downloading JSON metadata
[download] Destination: 10000000_1627597697309506_1016953736347516928_n.mp4-be0lrb2yu0.mp4
[download] 100% of 24.50MiB in 00:06

[+] Found Section :  LIVE CALL-Redacted

Preparing  lecture 1 of 2 download ...
Starting download ...
[Wistia] id00dq8r9p: Downloading JSON metadata
[download] Destination: SB CALL #1.mp4-id00dq8r9p.mp4
[download] 100% of 458.80MiB in 01:29
Preparing  lecture 2 of 2 download ...
Starting download ...
[Wistia] 6fs0429kf5: Downloading JSON metadata
[download] Destination: SB #2.mp4-6fs0429kf5.mp4
[download] 100% of 636.03MiB in 02:03

[+] Found Section :  STRATEGY VIDEOS

Preparing  lecture 1 of 2 download ...
Starting download ...
[Wistia] qck6xe1tz5: Downloading JSON metadata
[download] Destination: Recording #32.mp4-qck6xe1tz5.mp4
[download] 100% of 101.24MiB in 00:20
Preparing  lecture 2 of 2 download ...
Starting download ...
[Wistia] jiyaow067z: Downloading JSON metadata
[download] Destination: Recording #69.mp4-jiyaow067z.bin
[download] 100% of 40.27MiB in 00:14

[+] Found Section :  Case Redacted


[+] Found Section :  Redacted Case Study 


[+] Found Section :  Case Study - Redacted

Preparing  lecture 1 of 1 download ...
Starting download ...
[Wistia] gzw462lppi: Downloading JSON metadata
[download] Destination: Recording #2.mp4-gzw462lppi.bin
[download] 100% of 62.57MiB in 00:14

[+] Found Section :  Case Study - Redacted

sanitizing file names ...
[+]file name sanitation completed

[+] Download completed.Enjoy your course ***********
```

**Comment by barakagb** [comment]
Its still unclear for me which site you are downloading from .Kindly share the site
e.g https://stackskills.com ... this will help to find a solution.Thanks
